[package]
name = "tang-site-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tang = { path = "../tang" }
tang-tensor = { workspace = true }
tang-train = { workspace = true }
wasm-bindgen = "0.2"

[profile.release]
opt-level = "s"
lto = true
