[package]
name = "tang-sparse"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CSR/CSC sparse matrices and sparse solvers"

[dependencies]
tang = { workspace = true }
tang-la = { workspace = true }

[dev-dependencies]
approx = "0.5"
